2019-11-19 00:01:00,281 DEBUG 9771   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:46.880 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:01:00,324 DEBUG 9771   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:19.530 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:01:00,380 DEBUG 9771   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:39.240 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:30:18,653 DEBUG 11400   ---  [MainThread] - [GET] -> [/cms/theme/5] from:127.0.0.1 costs:61.910 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:30:18,685 DEBUG 11400   ---  [MainThread] - [GET] -> [/cms/theme/all] from:127.0.0.1 costs:14.400 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:30:18,836 DEBUG 11400   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:117.180 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:46:50,137 ERROR 12105   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 15, in get
    return jsonify(model)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Users/zhaochenxi/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/zhaochenxi/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/zhaochenxi/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/core.py", line 364, in default
    return dict(o)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/db.py", line 85, in __getitem__
    return getattr(self, key)
AttributeError: 'Product' object has no attribute 'theme_id'

2019-11-19 00:46:50,151 DEBUG 12105   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:85.800 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:46:50,485 ERROR 12105   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 39, in get_paginate
    return jsonify(models)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Users/zhaochenxi/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/zhaochenxi/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/zhaochenxi/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/core.py", line 364, in default
    return dict(o)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/db.py", line 85, in __getitem__
    return getattr(self, key)
AttributeError: 'Product' object has no attribute 'theme_id'

2019-11-19 00:46:50,487 DEBUG 12105   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:44.380 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:48:13,080 DEBUG 12138   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:142.990 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 00:48:13,265 DEBUG 12138   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:161.730 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:17:12,509 DEBUG 15374   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:104.410 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:17:12,542 DEBUG 15374   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:10.690 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:17:12,649 DEBUG 15374   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:71.040 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:17:28,668 DEBUG 15403   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:87.970 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:17:28,753 DEBUG 15403   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:57.680 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:18:16,441 DEBUG 15464   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:96.820 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:18:16,562 DEBUG 15464   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:74.320 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:18:16,674 DEBUG 15464   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:40.310 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:18:16,784 DEBUG 15464   ---  [MainThread] - [PUT] -> [/cms/category/hide/3] from:127.0.0.1 costs:72.360 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:18:29,190 DEBUG 15518   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:102.820 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:18:29,309 DEBUG 15518   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:104.950 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:00,894 DEBUG 15566   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:70.840 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:01,266 DEBUG 15566   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:7.460 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:01,303 DEBUG 15566   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:19.510 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:01,363 DEBUG 15566   ---  [MainThread] - [DELETE] -> [/cms/category/3] from:127.0.0.1 costs:26.480 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:29,866 DEBUG 15595   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:60.180 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:30,171 DEBUG 15595   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:18.770 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:30,249 DEBUG 15595   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:31.160 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:30,311 DEBUG 15595   ---  [MainThread] - [PUT] -> [/cms/category/show/1] from:127.0.0.1 costs:26.340 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:19:30,370 DEBUG 15595   ---  [MainThread] - [DELETE] -> [/cms/category/3] from:127.0.0.1 costs:35.060 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:01,549 DEBUG 15623   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:68.840 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:01,999 DEBUG 15623   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:30.960 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:02,087 DEBUG 15623   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:49.360 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:02,152 DEBUG 15623   ---  [MainThread] - [PUT] -> [/cms/category/show/1] from:127.0.0.1 costs:21.610 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:07,794 DEBUG 15649   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:57.870 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:08,064 DEBUG 15649   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:12.620 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:08,113 DEBUG 15649   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:35.910 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:08,170 DEBUG 15649   ---  [MainThread] - [PUT] -> [/cms/category/show/3] from:127.0.0.1 costs:46.620 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:19,622 DEBUG 15677   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:57.840 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:19,653 DEBUG 15677   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:18.900 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:19,725 DEBUG 15677   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:42.510 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:19,843 DEBUG 15677   ---  [MainThread] - [DELETE] -> [/cms/category/3] from:127.0.0.1 costs:100.730 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:36,002 DEBUG 15703   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:62.210 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:36,282 DEBUG 15703   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:11.330 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:36,379 DEBUG 15703   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:62.500 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:36,434 DEBUG 15703   ---  [MainThread] - [DELETE] -> [/cms/category/3] from:127.0.0.1 costs:27.930 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:47,204 DEBUG 15728   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:65.880 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:20:47,292 DEBUG 15728   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:76.120 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:03,473 DEBUG 15936   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:75.810 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:03,654 DEBUG 15936   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:155.140 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:16,025 DEBUG 15963   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:58.930 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:16,324 DEBUG 15963   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:22.690 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:16,399 DEBUG 15963   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:33.940 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:20,703 DEBUG 15963   ---  [MainThread] - [POST] -> [/cms/category] from:127.0.0.1 costs:4256.110 ms data:{
	param: {}, 
	body: {'img_id': 2, 'name': '蔬菜', 'summary': '蔬菜世界'}
} 
2019-11-19 15:50:59,500 DEBUG 15993   ---  [MainThread] - [GET] -> [/cms/category/3] from:127.0.0.1 costs:67.520 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:59,813 DEBUG 15993   ---  [MainThread] - [GET] -> [/cms/category/all] from:127.0.0.1 costs:26.950 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:50:59,926 DEBUG 15993   ---  [MainThread] - [GET] -> [/cms/category/paginate] from:127.0.0.1 costs:72.760 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 15:51:03,590 DEBUG 15993   ---  [MainThread] - [POST] -> [/cms/category] from:127.0.0.1 costs:3650.480 ms data:{
	param: {}, 
	body: {'img_id': 1, 'name': '水果', 'summary': '水果世界'}
} 
2019-11-19 18:46:14,562 DEBUG 16987   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:93960.100 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 18:50:40,511 DEBUG 16987   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:289.280 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 21:29:59,661 ERROR 17120   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
cymysql.err.InternalError: (1054, "Unknown column 'product.product' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 14, in get
    model = Product.get_model(pid, err_msg='相关产品未添加或已隐藏')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 29, in get_model
    model = cls.query.filter_by(id=id, soft=soft).first()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2888, in first
    ret = list(self[0:1])
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2680, in __getitem__
    return list(res)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
sqlalchemy.exc.InternalError: (cymysql.err.InternalError) (1054, "Unknown column 'product.product' in 'field list'") [SQL: 'SELECT product.create_time AS product_create_time, product.update_time AS product_update_time, product.delete_time AS product_delete_time, product.id AS product_id, product.name AS product_name, product.price AS product_price, product.stock AS product_stock, product.summary AS product_summary, product.category_id AS product_category_id, product.img_id AS product_img_id, product.product AS product_product \nFROM product \nWHERE product.id = %s AND product.delete_time IS NULL \n LIMIT %s'] [parameters: (3, 1)] (Background on this error at: http://sqlalche.me/e/2j85)

2019-11-19 21:29:59,666 DEBUG 17120   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:1967.670 ms data:{
	param: {}, 
	body: {}
} 
2019-11-19 21:29:59,957 ERROR 17120   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
cymysql.err.InternalError: (1054, "Unknown column 'product.product' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 38, in get_paginate
    models = Product.get_paginate_models(start, count, q, soft=False, err_msg='相关产品不存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 55, in get_paginate_models
    total = statement.count()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3223, in count
    return self.from_self(col).scalar()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2976, in scalar
    ret = self.one()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2947, in one
    ret = self.one_or_none()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2917, in one_or_none
    ret = list(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
sqlalchemy.exc.InternalError: (cymysql.err.InternalError) (1054, "Unknown column 'product.product' in 'field list'") [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT product.create_time AS product_create_time, product.update_time AS product_update_time, product.delete_time AS product_delete_time, product.id AS product_id, product.name AS product_name, product.price AS product_price, product.stock AS product_stock, product.summary AS product_summary, product.category_id AS product_category_id, product.img_id AS product_img_id, product.product AS product_product \nFROM product) AS anon_1'] (Background on this error at: http://sqlalche.me/e/2j85)

2019-11-19 21:29:59,960 DEBUG 17120   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:21.590 ms data:{
	param: {}, 
	body: {}
} 
