2019-11-17 00:00:04,335 DEBUG 82887   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:39.100 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:00:04,774 DEBUG 82887   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:55.020 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:00:07,232 ERROR 82887   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1048, "Column 'price' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 51, in create
    Product.add_model(form.data, err_msg='相关商品已存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 167, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1048, "Column 'price' cannot be null") [SQL: 'INSERT INTO product (create_time, update_time, delete_time, name, price, stock, summary, category_id, theme_id, img_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 17, 0, 0, 7, 150979), datetime.datetime(2019, 11, 17, 0, 0, 7, 151030), None, '芹菜1', None, 0, '芹菜好吃吗', 1, 1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-17 00:00:07,243 DEBUG 82887   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:2438.030 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:02:31,058 DEBUG 82978   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:33.170 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:02:31,501 DEBUG 82978   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:37.200 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:02:31,628 ERROR 82978   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1048, "Column 'price' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 51, in create
    Product.add_model(form.data, err_msg='相关商品已存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 167, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1048, "Column 'price' cannot be null") [SQL: 'INSERT INTO product (create_time, update_time, delete_time, name, price, stock, summary, category_id, theme_id, img_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 17, 0, 2, 31, 570476), datetime.datetime(2019, 11, 17, 0, 2, 31, 570515), None, '芹菜1', None, 0, '芹菜好吃吗', 1, 1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-17 00:02:31,631 DEBUG 82978   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:102.950 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:04:29,800 DEBUG 83026   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:42.080 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:04:30,307 DEBUG 83026   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:71.180 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:04:30,740 ERROR 83026   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1048, "Column 'price' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 51, in create
    Product.add_model(form.data, err_msg='相关商品已存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 167, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1048, "Column 'price' cannot be null") [SQL: 'INSERT INTO product (create_time, update_time, delete_time, name, price, stock, summary, category_id, theme_id, img_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 17, 0, 4, 30, 527436), datetime.datetime(2019, 11, 17, 0, 4, 30, 527467), None, '芹菜1', None, 0, '芹菜好吃吗', 1, 1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-17 00:04:30,743 DEBUG 83026   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:310.800 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:05:22,494 DEBUG 83120   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:42.170 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:05:22,871 DEBUG 83120   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:54.700 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:05:26,879 ERROR 83120   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1048, "Column 'price' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 51, in create
    Product.add_model(form.data, err_msg='相关商品已存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 167, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1048, "Column 'price' cannot be null") [SQL: 'INSERT INTO product (create_time, update_time, delete_time, name, price, stock, summary, category_id, theme_id, img_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 17, 0, 5, 26, 845152), datetime.datetime(2019, 11, 17, 0, 5, 26, 845209), None, '芹菜1', None, 0, '芹菜好吃吗', 1, 1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-17 00:05:26,881 DEBUG 83120   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:3984.090 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:05:39,201 DEBUG 83155   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:33.670 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:05:39,633 DEBUG 83155   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:50.750 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:08:04,771 ERROR 83155   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1048, "Column 'price' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 51, in create
    Product.add_model(form.data, err_msg='相关商品已存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 167, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1048, "Column 'price' cannot be null") [SQL: 'INSERT INTO product (create_time, update_time, delete_time, name, price, stock, summary, category_id, theme_id, img_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 17, 0, 8, 4, 716722), datetime.datetime(2019, 11, 17, 0, 8, 4, 716875), None, '芹菜1', None, 0, '芹菜好吃吗', 1, 1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-17 00:08:04,779 DEBUG 83155   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:145057.510 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:12:42,318 DEBUG 83323   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:34.910 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:12:42,676 DEBUG 83323   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:51.230 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:14:04,531 ERROR 83323   ---  [MainThread] - Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
cymysql.err.IntegrityError: (1048, "Column 'price' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/api/cms/product.py", line 51, in create
    Product.add_model(form.data, err_msg='相关商品已存在')
  File "/Users/zhaochenxi/Home/PythonProjects/flask-api/snack-api-lin/app/models/base.py", line 167, in add_model
    cls.create(**data, commit=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/lin/interface.py", line 149, in create
    db.session.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 135, in execute
    self.errorhandler(exc, value)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 37, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 117, in errorhandler
    raise errorvalue
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 130, in execute
    self._query(query)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/cursors.py", line 240, in _query
    conn.query(q)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/connections.py", line 346, in query
    self._result = MySQLResult(self)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 270, in __init__
    self.first_packet = MysqlPacket(self.connection)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/packet.py", line 66, in __init__
    raise_mysql_exception(self.__data)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/zhaochenxi/.local/share/virtualenvs/snack-api-lin-g_CxUc26/lib/python3.6/site-packages/cymysql/err.py", line 141, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (cymysql.err.IntegrityError) (1048, "Column 'price' cannot be null") [SQL: 'INSERT INTO product (create_time, update_time, delete_time, name, price, stock, summary, category_id, theme_id, img_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2019, 11, 17, 0, 14, 4, 481845), datetime.datetime(2019, 11, 17, 0, 14, 4, 481910), None, '芹菜1', None, 0, '芹菜好吃吗', 1, 1, 2)] (Background on this error at: http://sqlalche.me/e/gkpj)

2019-11-17 00:14:04,535 DEBUG 83323   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:81829.960 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:18:54,674 DEBUG 83366   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:43.560 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:18:55,021 DEBUG 83366   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:45.050 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:19:10,781 DEBUG 83366   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:15729.240 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.01', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:19:29,349 DEBUG 83418   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:37.300 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:19:29,688 DEBUG 83418   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:48.600 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:19:32,025 DEBUG 83418   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:2314.550 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.019', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:19:52,561 DEBUG 83449   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:36.280 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:19:52,917 DEBUG 83449   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:46.850 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:19:52,956 DEBUG 83449   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:12.250 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.0', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:20:49,725 DEBUG 83506   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:38.510 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:20:50,078 DEBUG 83506   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:57.480 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:20:50,146 DEBUG 83506   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:29.800 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1.0', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:21:02,028 DEBUG 83539   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:41.190 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:21:02,352 DEBUG 83539   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:41.500 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:21:02,380 DEBUG 83539   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:13.140 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '1', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:21:51,401 DEBUG 83570   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:36.280 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:21:51,776 DEBUG 83570   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:76.020 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:21:51,824 DEBUG 83570   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:12.020 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': 'knk', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:22:03,980 DEBUG 83597   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:35.270 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:22:04,348 DEBUG 83597   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:47.250 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:22:04,385 DEBUG 83597   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:13.460 ms data:{
	param: {}, 
	body: {'category_id': 1, 'img_id': 2, 'name': '芹菜1', 'price_str': '', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 1}
} 
2019-11-17 00:23:40,635 DEBUG 83643   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:34.550 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:23:41,037 DEBUG 83643   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:60.080 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:23:41,084 DEBUG 83643   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:19.250 ms data:{
	param: {}, 
	body: {'category_id': 2, 'img_id': 2, 'name': '芹菜2', 'price_str': '', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 3}
} 
2019-11-17 00:23:50,004 DEBUG 83672   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:41.660 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:23:50,352 DEBUG 83672   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:44.320 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:23:50,430 DEBUG 83672   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:54.790 ms data:{
	param: {}, 
	body: {'category_id': 2, 'img_id': 2, 'name': '芹菜2', 'price_str': '2.21', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 3}
} 
2019-11-17 00:24:30,042 DEBUG 83710   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:34.010 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:24:30,375 DEBUG 83710   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:48.950 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:24:30,448 DEBUG 83710   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:58.140 ms data:{
	param: {}, 
	body: {'category_id': 2, 'img_id': 2, 'name': '芹菜2', 'price_str': '2.21', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 3}
} 
2019-11-17 00:24:30,498 DEBUG 83710   ---  [MainThread] - [PUT] -> [/cms/product/1] from:127.0.0.1 costs:11.960 ms data:{
	param: {}, 
	body: {'category_id': 2, 'img_id': 3, 'name': '芹菜1', 'price': '1.20', 'stock': 0, 'summary': '芹菜好吃吗'}
} 
2019-11-17 00:25:07,635 DEBUG 83739   ---  [MainThread] - [GET] -> [/cms/product/3] from:127.0.0.1 costs:36.110 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:25:07,989 DEBUG 83739   ---  [MainThread] - [GET] -> [/cms/product/paginate] from:127.0.0.1 costs:52.170 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 00:25:08,073 DEBUG 83739   ---  [MainThread] - [POST] -> [/cms/product] from:127.0.0.1 costs:51.860 ms data:{
	param: {}, 
	body: {'category_id': 2, 'img_id': 2, 'name': '芹菜2', 'price_str': '2.21', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 3}
} 
2019-11-17 00:25:08,173 DEBUG 83739   ---  [MainThread] - [PUT] -> [/cms/product/1] from:127.0.0.1 costs:60.970 ms data:{
	param: {}, 
	body: {'category_id': 2, 'img_id': 1, 'name': '芹菜1', 'price_str': '1.20', 'stock': 0, 'summary': '芹菜好吃吗', 'theme_id': 3}
} 
2019-11-17 10:51:32,058 DEBUG 84525   ---  [MainThread] - [GET] -> [/cms/theme/1] from:127.0.0.1 costs:72.520 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:51:32,137 DEBUG 84525   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:35.260 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:51:32,201 DEBUG 84525   ---  [MainThread] - [PUT] -> [/cms/theme/2] from:127.0.0.1 costs:52.300 ms data:{
	param: {}, 
	body: {'description': '美味水果世界', 'head_img_id': 1, 'name': '水果世界', 'topic_img_id': 1}
} 
2019-11-17 10:51:32,599 DEBUG 84525   ---  [MainThread] - [PUT] -> [/cms/theme/hide/2] from:127.0.0.1 costs:19.180 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:51:32,647 DEBUG 84525   ---  [MainThread] - [PUT] -> [/cms/theme/show/2] from:127.0.0.1 costs:18.480 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:52:29,033 DEBUG 84599   ---  [MainThread] - [GET] -> [/cms/theme/1] from:127.0.0.1 costs:54.150 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:52:29,090 DEBUG 84599   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:35.480 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:52:29,127 DEBUG 84599   ---  [MainThread] - [POST] -> [/cms/theme] from:127.0.0.1 costs:27.180 ms data:{
	param: {}, 
	body: {'description': '美味水果世界, 多汁多甜多嫩', 'head_img_id': 2, 'name': '水果世界', 'topic_img_id': 2}
} 
2019-11-17 10:52:29,556 DEBUG 84599   ---  [MainThread] - [PUT] -> [/cms/theme/2] from:127.0.0.1 costs:49.150 ms data:{
	param: {}, 
	body: {'description': '美味水果世界', 'head_img_id': 1, 'name': '水果世界', 'topic_img_id': 1}
} 
2019-11-17 10:52:29,631 DEBUG 84599   ---  [MainThread] - [PUT] -> [/cms/theme/hide/2] from:127.0.0.1 costs:30.670 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:52:29,720 DEBUG 84599   ---  [MainThread] - [PUT] -> [/cms/theme/show/2] from:127.0.0.1 costs:61.320 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:53:23,855 DEBUG 84660   ---  [MainThread] - [GET] -> [/cms/theme/1] from:127.0.0.1 costs:45.210 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:53:23,906 DEBUG 84660   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:36.490 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:53:24,025 DEBUG 84660   ---  [MainThread] - [POST] -> [/cms/theme] from:127.0.0.1 costs:73.890 ms data:{
	param: {}, 
	body: {'description': '炒货无敌', 'head_img_id': 2, 'name': '炒货天堂', 'topic_img_id': 2}
} 
2019-11-17 10:53:24,086 DEBUG 84660   ---  [MainThread] - [PUT] -> [/cms/theme/2] from:127.0.0.1 costs:29.780 ms data:{
	param: {}, 
	body: {'description': '美味水果世界', 'head_img_id': 1, 'name': '水果世界', 'topic_img_id': 1}
} 
2019-11-17 10:53:24,393 DEBUG 84660   ---  [MainThread] - [PUT] -> [/cms/theme/hide/2] from:127.0.0.1 costs:19.370 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 10:53:24,448 DEBUG 84660   ---  [MainThread] - [PUT] -> [/cms/theme/show/2] from:127.0.0.1 costs:16.100 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:37:13,947 DEBUG 93334   ---  [MainThread] - [GET] -> [/cms/theme/1] from:127.0.0.1 costs:55.200 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:37:14,154 DEBUG 93334   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:159.030 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:37:14,238 DEBUG 93334   ---  [MainThread] - [POST] -> [/cms/theme] from:127.0.0.1 costs:18.070 ms data:{
	param: {}, 
	body: {'description': '炒货无敌', 'head_img_id': 2, 'name': '炒货天堂', 'topic_img_id': 2}
} 
2019-11-17 12:37:14,584 DEBUG 93334   ---  [MainThread] - [PUT] -> [/cms/theme/2] from:127.0.0.1 costs:25.820 ms data:{
	param: {}, 
	body: {'description': '美味水果世界', 'head_img_id': 1, 'name': '水果世界', 'topic_img_id': 1}
} 
2019-11-17 12:37:14,720 DEBUG 93334   ---  [MainThread] - [PUT] -> [/cms/theme/hide/2] from:127.0.0.1 costs:67.480 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:37:14,874 DEBUG 93334   ---  [MainThread] - [PUT] -> [/cms/theme/show/2] from:127.0.0.1 costs:48.500 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:06,522 DEBUG 93399   ---  [MainThread] - [GET] -> [/cms/theme/3] from:127.0.0.1 costs:42.330 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:06,594 DEBUG 93399   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:58.350 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:06,635 DEBUG 93399   ---  [MainThread] - [POST] -> [/cms/theme] from:127.0.0.1 costs:13.470 ms data:{
	param: {}, 
	body: {'description': '炒货无敌', 'head_img_id': 2, 'name': '炒货天堂', 'topic_img_id': 2}
} 
2019-11-17 12:39:07,051 DEBUG 93399   ---  [MainThread] - [PUT] -> [/cms/theme/2] from:127.0.0.1 costs:14.240 ms data:{
	param: {}, 
	body: {'description': '美味水果世界', 'head_img_id': 1, 'name': '水果世界', 'topic_img_id': 1}
} 
2019-11-17 12:39:07,126 DEBUG 93399   ---  [MainThread] - [PUT] -> [/cms/theme/hide/2] from:127.0.0.1 costs:32.580 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:07,202 DEBUG 93399   ---  [MainThread] - [PUT] -> [/cms/theme/show/2] from:127.0.0.1 costs:32.640 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:28,668 DEBUG 93426   ---  [MainThread] - [GET] -> [/cms/theme/3] from:127.0.0.1 costs:37.420 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:28,751 DEBUG 93426   ---  [MainThread] - [GET] -> [/cms/theme/paginate] from:127.0.0.1 costs:70.390 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:28,831 DEBUG 93426   ---  [MainThread] - [POST] -> [/cms/theme] from:127.0.0.1 costs:45.700 ms data:{
	param: {}, 
	body: {'head_img_id': 2, 'name': '炒货天堂', 'summary': '炒货无敌', 'topic_img_id': 2}
} 
2019-11-17 12:39:29,266 DEBUG 93426   ---  [MainThread] - [PUT] -> [/cms/theme/2] from:127.0.0.1 costs:30.990 ms data:{
	param: {}, 
	body: {'head_img_id': 1, 'name': '水果世界', 'summary': '美味水果世界', 'topic_img_id': 1}
} 
2019-11-17 12:39:29,378 DEBUG 93426   ---  [MainThread] - [PUT] -> [/cms/theme/hide/2] from:127.0.0.1 costs:89.470 ms data:{
	param: {}, 
	body: {}
} 
2019-11-17 12:39:29,453 DEBUG 93426   ---  [MainThread] - [PUT] -> [/cms/theme/show/2] from:127.0.0.1 costs:8.860 ms data:{
	param: {}, 
	body: {}
} 
